# Generated by Django 5.2.7 on 2025-10-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBestiarioHP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creature',
            new_name='Criatura',
        ),
        migrations.RenameModel(
            old_name='DangerCategory',
            new_name='Peligro',
        ),
    ]
