# Generated by Django 5.2.7 on 2025-10-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBestiarioHP', '0002_rename_creature_criatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criatura',
            name='danger_categories',
        ),
        migrations.AddField(
            model_name='criatura',
            name='categoria_peligro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBestiarioHP.peligro'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='criatura',
            name='raza',
        ),
        migrations.AddField(
            model_name='criatura',
            name='raza',
            field=models.ManyToManyField(to='appBestiarioHP.raza'),
        ),
    ]
