# Generated by Django 5.2.7 on 2025-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBestiarioHP', '0003_remove_criatura_danger_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criatura',
            name='caracteristicas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criatura',
            name='donde_se_encuentra',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criatura',
            name='raza',
            field=models.ManyToManyField(blank=True, to='appBestiarioHP.raza'),
        ),
    ]
